<?php
/**
 * 【文章管理-增删改业务逻辑模型】
 * Created by PhpStorm.
 * User: ZH
 * Date: 2018/11/21
 * Time: 15:16
 */

namespace app\models\admin;

use app\models\BaseModel;

class Article extends BaseModel
{
    public static $table = 'article';
    public $title, $description, $thum, $content, $classify, $status, $top;

    public function __construct()
    {
        parent::__construct();
        parent::$logParam['module'] = '内容管理-文章管理';
    }

    /**
     * 规则校验
     * @return array
     */
    public function rules()
    {
        return [
            [['title', 'description', 'content', 'classify'], 'required'],
        ];
    }

    /**
     * 地址标签
     * @return array
     */
    public function attributeLabels()
    {
        return [
            'title'       => '文章标题',
            'description' => '文章描述',
            'thum'        => '缩略图',
            'content'     => '内容',
            'classify'    => '文章类别',
        ];
    }

    /**
     * 表名
     * @return mixed|string
     */
    public static function tableName()
    {
        return self::$table; // TODO: Change the autogenerated stub
    }

    /**
     * 文章新增和编辑
     * @param $data
     * @return bool|string|void
     */
    public function atrAddOrEdit($data)
    {
        $action = !empty($data['id']) && isset($data['id']) ? 'edit' : 'add';
        parent::$logParam['action'] = $action == 'edit' ? EDIT : ADD;
        parent::$logParam['cmd'] = '文章列表';
        try {
            //获取类名
            $path = str_replace("\\", "/", $this::className());
            //输入验证
            $this->load([basename($path) => $data]);
            if (!$this->validate()) {
                $error = (current($this->getFirstErrors()));
                throw new \Exception($error, parent::$isValidCode);
            }

            if (!isset($data['thum'])) {
//                throw new \Exception('请上传文章缩略图。');
                $data['thum'] = '';
            }
            //如果是编辑判断图片和内容中的图片是否被修改
            if ($action == 'edit') {
                $where = 'id=' . $data['id'];
                $info = $this->getS(self::$table, 'thum,content', 1, $where);
                if (!empty($info['thum']) && $data['thum'] != $info['thum']) {//删除原图片
                    unlink('..' . $info['thum']);
                }
                preg_match_all('/<img.*?src="(\/.*?)".*?>/is', $info['content'], $c1);
                preg_match_all('/<img.*?src="(\/.*?)".*?>/is', $data['content'], $c2);
                $tmp1 = [];
                $tmp2 = [];
                //获取原来内容图片集合
                foreach ($c1[1] as $k1 => $v1) {
                    $tmp1[$k1] = $v1;
                }
                ////获取修改内容图片集合
                foreach ($c2[1] as $k2 => $v2) {
                    $tmp2[$k2] = $v2;
                }
                //获取前后图片差集
                $diff = array_diff($tmp1, $tmp2);
                if (!empty($diff)) {
                    foreach ($diff as $d) {
                        unlink('..' . $d);
                    }
                }
            } else {
				$data['time'] = date('Y-m-d H:i:s', time());
			}
			
			$data['update_time'] = date('Y-m-d H:i:s', time());
            $data['top'] = $data['top'] == 1 ? 'checked' : '';
            $this->addOrEdit(self::$table, $data, 'id', $action);
            parent::saveOptLog(1);
            return true;
        } catch (\Exception $e) {
            return parent::catchException($e, $this);
        }
    }

    /**
     * 文章列表
     * @param $page '当前页'
     * @param $limit '每页显示条数'
     * @param $name '查询条件 标题'
     * @return array
     * @throws \yii\db\Exception
     */
    public function lists($page, $limit, $name, $type)
    {
        $data = [];//用于返回的数据
        $data['code'] = 0;
        $data['msg'] = '';
        $data['count'] = $this->getS(self::$table, 'count(*)', 2);
        $extra = "order by id desc limit " . ($page - 1) * $limit . "," . $limit;
        //开启模糊查询
        $where = '';
        $param = [];
        if (!empty($name)) {
            $where .= " title like :name AND";
            $param['name'] = '%' . trim($name) . '%';
        }
        if ($type != 0) {
            $where .= " classify =:classify AND";
            $param['classify'] = $type;
        }
        $where .= ' 1=1';
        $data['data'] = $this->getS(self::$table, '*', 0, $where, $param, $extra);
        return $data;
    }

    /**
     * 批量删除操作
     * @param $ids 'id,多个id用,隔开'
     * @return bool
     * @throws \yii\db\Exception
     */
    public function ArtDels($ids)
    {
        parent::$logParam['action'] = DELETE;
        parent::$logParam['cmd'] = '文章列表';
        $this->picDelete($ids);
        $sql = "DELETE FROM " . self::$table . " WHERE (id IN ($ids))";
        $ex = parent::$handle->createCommand($sql);
        $ex->execute();
        parent::saveOptLog(1);
        return true;
    }

    /**
     * 删除操作删除图片
     */
    public function picDelete($ids)
    {
        $sql = "SELECT id,thum,content FROM " . self::$table . " WHERE (id IN ($ids))";
        $ex = parent::$handle->createCommand($sql);
        $data = $ex->queryAll();
        $pic = array_column($data, 'thum');
        $c_pic = array_column($data, 'content');
        foreach ($pic as $v) {//删除缩略图
			if(!empty($v)){
				unlink('..' . $v);
			}
        }
        foreach ($c_pic as $c) {
            preg_match_all('/<img.*?src="(\/.*?)".*?>/is', $c, $arr);
            foreach ($arr[1] as $p) {
                unlink('..' . $p);
            }
        }
    }

    //置顶操作
    public function setTop($post)
    {
        $status = $post['top'] == 'checked' ? $post['top'] : '';
        parent::$logParam['action'] = $status == 'checked' ? '置顶' : '取消置顶';
        parent::$logParam['cmd'] = '文章列表';
        //组装数据
        $data['id'] = $post['id'];
        $data['top'] = $status;
        $this->addOrEdit(self::$table, $data, 'id');
        parent::saveOptLog(1);
        return true;
    }

    //修改状态操作
    public function setStatus($post)
    {
        $status = $post['status'] == 'checked' ? $post['status'] : '';
        parent::$logParam['action'] = $status == 'checked' ? '在线' : '隐藏';
        parent::$logParam['cmd'] = '文章列表-状态设置';
        //组装数据
        $data['id'] = $post['id'];
        $data['status'] = $status;
        $this->addOrEdit(self::$table, $data, 'id');
        parent::saveOptLog(1);
        return true;
    }

}