<?php
/**
 * 【招聘信息业务逻辑层】
 * Created by PhpStorm.
 * User: ZH
 * Date: 2018/11/26
 * Time: 9:50
 */

namespace app\models\admin;

use app\models\BaseModel;

class Recruit extends BaseModel
{
    public static $recruit = 'recruit';
    public $name, $num, $money, $content;

    public function __construct()
    {
        parent::__construct();
    }

    /**
     * 规则校验
     * @return array
     */
    public function rules()
    {
        return [
            [['name', 'num', 'money', 'content'], 'required'],
            [['num'], 'integer', 'min' => 1],
            [['money'], 'string', 'min' => 1, 'when' => function () {
                return $this->money != '面议';
            }],
        ];
    }

    /**
     * 地址标签
     * @return array
     */
    public function attributeLabels()
    {
        return [
            'name'    => '岗位名称',
            'num'     => '岗位人数',
            'money'   => '月薪',
            'content' => '岗位需求',
        ];
    }

    /**
     * 表名
     * @return mixed|string
     */
    public static function tableName()
    {
        return self::$recruit; // TODO: Change the autogenerated stub
    }

    /**
     * 招聘信息新增和编辑
     * @param $data
     * @return bool|string|void
     */
    public function recruitAddOrEdit($data)
    {
        $action = !empty($data['id']) && isset($data['id']) ? 'edit' : 'add';
        parent::$logParam['module'] = '内容管理';
        parent::$logParam['action'] = $action == 'edit' ? EDIT : ADD;
        parent::$logParam['cmd'] = '发布招聘';
        try {
            //获取类名
            $path = str_replace("\\", "/", $this::className());
            //输入验证
            $this->load([basename($path) => $data]);
            if (!$this->validate()) {
                $error = (current($this->getFirstErrors()));
                throw new \Exception($error, parent::$isValidCode);
            }
            if ($action == 'add') {//新建url唯一
                unset($data['id']);
				$data['time'] = date('Y-m-d H:i:s', time());
            } else {
                $where = 'id=' . $data['id'];
                $info = $this->getS(self::$recruit, 'content', 1, $where);
                preg_match_all('/<img.*?src="(\/.*?)".*?>/is', $info['content'], $c1);
                preg_match_all('/<img.*?src="(\/.*?)".*?>/is', $data['content'], $c2);
                $tmp1 = [];
                $tmp2 = [];
                //获取原来内容图片集合
                foreach ($c1[1] as $k1 => $v1) {
                    $tmp1[$k1] = $v1;
                }
                ////获取修改内容图片集合
                foreach ($c2[1] as $k2 => $v2) {
                    $tmp2[$k2] = $v2;
                }
                //获取前后图片差集
                $diff = array_diff($tmp1, $tmp2);
                if (!empty($diff)) {
                    foreach ($diff as $d) {
                        unlink('..' . $d);
                    }
                }
            }
            $this->addOrEdit(self::$recruit, $data, 'id', $action);
            parent::saveOptLog(1);
            return true;
        } catch (\Exception $e) {
            return parent::catchException($e, $this);
        }
    }

    /**
     * 招聘信息列表
     * @param $page '当前页'
     * @param $limit '每页显示条数'
     * @param $name '查询条件 标题'
     * @return array
     * @throws \yii\db\Exception
     */
    public function lists($page, $limit, $name)
    {
        $data = [];//用于返回的数据
        $data['code'] = 0;
        $data['msg'] = '';
        $data['count'] = $this->getS(self::$recruit, 'count(*)', 2);
        $extra = "order by id desc limit " . ($page - 1) * $limit . "," . $limit;
        //开启模糊查询
        $where = '';
        $param = [];
        if (!empty($name)) {
            $where .= " name like :name AND";
            $param['name'] = '%' . trim($name) . '%';
        }
        $where .= ' 1=1';
        $data['data'] = $this->getS(self::$recruit, '*', 0, $where, $param, $extra);
        return $data;
    }

    /**
     * 批量删除操作
     * @param $ids 'id,多个id用,隔开'
     * @return bool
     * @throws \yii\db\Exception
     */
    public function RecruitDel($ids)
    {
        parent::$logParam['module'] = '内容管理';
        parent::$logParam['action'] = DELETE;
        parent::$logParam['cmd'] = '发布招聘';
        $this->picDelete($ids);
        $sql = "DELETE FROM " . self::$recruit . " WHERE (id IN ($ids))";
        $ex = parent::$handle->createCommand($sql);
        $ex->execute();
        parent::saveOptLog(1);
        return true;
    }

    /**
     * 删除操作删除图片
     */
    public function picDelete($ids)
    {
        $sql = "SELECT id,content FROM " . self::$recruit . " WHERE (id IN ($ids))";
        $ex = parent::$handle->createCommand($sql);
        $data = $ex->queryAll();
        $c_pic = array_column($data, 'content');
        foreach ($c_pic as $c) {
            preg_match_all('/<img.*?src="(\/.*?)".*?>/is', $c, $arr);
            foreach ($arr[1] as $p) {
                unlink('..' . $p);
            }
        }
    }
}