<?php
/**
 * 【友情链接业务逻辑层】
 * Created by PhpStorm.
 * User: ZH
 * Date: 2018/11/24 0024
 * Time: 15:50
 */

namespace app\models\admin;

use app\models\BaseModel;
use yii\db\Exception;

class Seo extends BaseModel
{
    public static $seo   = 'seo';
    public static $basic = 'basic';
    public $title, $keywords, $description;

    public function __construct()
    {
        parent::__construct();
        parent::$logParam['module'] = '碎片管理';
    }

    /**
     * 规则校验
     * @return array
     */
    public function rules()
    {
        return [
            [['title', 'keywords', 'description'], 'required'],
            [['title', 'keywords','description'], 'checkSeo'],
        ];
    }

    /**
     * 地址标签
     * @return array
     */
    public function attributeLabels()
    {
        return [
            'title'         => '标题',
            'keywords'      => '关键字',
            'description'   => '描述',
        ];
    }

    /**
     * 表名
     * @return mixed|string
     */
    public static function tableName()
    {
        return self::$seo; // TODO: Change the autogenerated stub
    }

    //校验数据
    public function checkSeo($attribute)
    {
        switch ($attribute) {
            case 'title':
                if (strlen(trim($this->title)) > 80) {
                    $this->addError($attribute, '标题不超过80个字符。');
                }
                break;
            case 'keywords':
                if (strlen(trim($this->keywords)) > 100) {
                    $this->addError($attribute, '关键字不超过100个字符。');
                }
                break;
            case 'description':
                if (strlen(trim($this->description)) > 200) {
                    $this->addError($attribute, '描述不超过200个字符。');
                }
                break;
        }
    }

    /**
     * SEO新增和编辑
     * @param $data
     * @return bool|string|void
     */
    public function SeoAddOrEdit($data)
    {
        parent::$logParam['action'] = EDIT;
        parent::$logParam['cmd'] = '站点管理-SEO设置';
        try {
            $path = str_replace("\\", "/", $this::className());
            //输入验证
            $this->load([basename($path) => $data]);
            if (!$this->validate()) {
                $error = (current($this->getFirstErrors()));
                throw new \Exception($error, parent::$isValidCode);
            }
            $this->addOrEdit(self::$seo, $data, 'id');
            parent::saveOptLog(1);
            return true;
        } catch (\Exception $e) {
            return parent::catchException($e, $this);
        }
    }

    /**
     * SEO列表
     * @return array
     * @throws \yii\db\Exception
     */
    public function lists()
    {
        return $this->getS(self::$seo, '*', 1);
    }

    //获取公司信息列表
    public function getBasic()
    {
        return $this->getS(self::$basic,'*',1);
    }

    /**
     * URL新增和编辑
     * @param $data
     * @return bool|string|void
     */
    public function basicEdit($data)
    {
        parent::$logParam['action'] = EDIT;
        parent::$logParam['cmd'] = '站点管理-基本信息';
        try {
            if (!isset($data['logo'])) {
                throw new \Exception('请上公司LOGO。');
            }
            if (empty($data['tel'])) {
//                $this->addError('tel', 'TEL不能为空。');
//                return $this;
                throw new \Exception('TEL不能为空。');
            }
            $this->picDelete();
            $this->addOrEdit(self::$basic, $data, 'id');
            parent::saveOptLog(1);
            return true;
        } catch (\Exception $e) {
            return parent::catchException($e, $this);
        }
    }

    /**
     * 删除操作删除图片
     */
    public function picDelete()
    {
        $logo = $this->getS(self::$basic,'logo',2);
        unlink('..' . $logo);
    }


}